package my.guide.theescapists2

import android.os.Bundle
import android.view.*
import androidx.fragment.app.Fragment
import androidx.appcompat.widget.SearchView
import androidx.navigation.Navigation
import androidx.recyclerview.widget.LinearLayoutManager
import androidx.recyclerview.widget.RecyclerView
import my.guide.theescapists2.databinding.FragmentMainCraftBinding
import my.guide.theescapists2.recycler.ItemAdapter
import my.guide.theescapists2.recycler.Items
import java.util.*
import kotlin.collections.ArrayList


class FragmentMainCraft : Fragment() {
    private lateinit var adapter: ItemAdapter
    private lateinit var recyclerView: RecyclerView
    private lateinit var itemsArrayList: ArrayList<Items>
    private lateinit var searchView: SearchView
    lateinit var imageId: Array<Int>
    lateinit var name: Array<String>
    lateinit var craft: Array<String>
    lateinit var intelligence: Array<String>
    lateinit var imOneId: Array<Int>
    lateinit var imTwoId: Array<Int>
    lateinit var imThreeId: Array<Int>


    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        val binding = FragmentMainCraftBinding.inflate(inflater)
        binding.bottomNavigation.selectedItemId = R.id.craftId
        binding.bottomNavigation.setOnItemSelectedListener {
            when (it.itemId) {
                R.id.mapsId -> {
                    val view = binding.FragmentMain
                    Navigation.findNavController(view)
                        .navigate(R.id.action_fragmentMainCraft_to_fragmentMap)
                    true
                }
                R.id.componentId -> {
                    val view = binding.FragmentMain
                    Navigation.findNavController(view)
                        .navigate(R.id.action_fragmentMainCraft_to_fragmentWallpaper)
                    true
                }
                else -> false
            }
        }
        return binding.root
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        dataInitialize()
        val layoutManager = LinearLayoutManager(context)
        recyclerView = view.findViewById(R.id.recycler_view)
        searchView = view.findViewById(R.id.searchView)
        recyclerView.layoutManager = layoutManager
        recyclerView.setHasFixedSize(true)
        adapter = ItemAdapter(itemsArrayList)
        recyclerView.adapter = adapter

        searchView.setOnQueryTextListener(object : SearchView.OnQueryTextListener {
            override fun onQueryTextSubmit(query: String?): Boolean {
                return false
            }

            override fun onQueryTextChange(newText: String?): Boolean {
                filterList(newText)
                return true
            }

        })

    }

    private fun filterList(query: String?) {
        if (query != null) {
            val filteredList = ArrayList<Items>()
            for (i in itemsArrayList) {
                if (i.name.lowercase(Locale.ROOT).contains(query.lowercase())) {
                    filteredList.add(i)
                }
            }
            if (filteredList.isEmpty()) {
            } else {
                adapter.setFilteredList(filteredList)
            }
        }
    }

    private fun dataInitialize() {
        itemsArrayList = arrayListOf<Items>()

        imOneId = arrayOf(
            R.drawable.timber,
            R.drawable.sock,
            R.drawable.glassshard,
            R.drawable.comb,
            R.drawable.timber,
            R.drawable.whip,
            R.drawable.bedsheet,
            R.drawable.broomhandle,
            R.drawable.razorblade,
            R.drawable.knuckleduster,
            R.drawable.cup,
            R.drawable.oldbox,
            R.drawable.wire,
            R.drawable.broomhandle,
            R.drawable.baseball,
            R.drawable.battery,
            R.drawable.energymodule,
            R.drawable.metalbaton,
            R.drawable.sock,
            R.drawable.timber,
            R.drawable.toolhandle,
            R.drawable.flimsypickaxe,
            R.drawable.lightweightpickaxe,
            R.drawable.toolhandle,
            R.drawable.flimsyshovel,
            R.drawable.lightweightshovel,
            R.drawable.file,
            R.drawable.flimsycutters,
            R.drawable.lightweightcutters,
            R.drawable.sturdyshovel,
            R.drawable.dentalfloss,
            R.drawable.jarofink,
            R.drawable.inmateoutfit,
            R.drawable.inmateoutfit,
            R.drawable.inmateoutfit,
            R.drawable.inmateoutfit,
            R.drawable.sheetofmetal,
            R.drawable.papermache,
            R.drawable.papermache,
            R.drawable.wire,
            R.drawable.pillow,
            R.drawable.foil,
            R.drawable.foil,
            R.drawable.magazine,
            R.drawable.crowbar,
            R.drawable.grapplehead,
            R.drawable.bedsheet,
            R.drawable.wax,
            R.drawable.rolloftoiletpaper,
            R.drawable.comb,
            R.drawable.keymould,
            R.drawable.wadofputty,
            R.drawable.keycards,
            R.drawable.keycardmould,
            R.drawable.toothpaste,
            R.drawable.timber,
            R.drawable.timber,
            R.drawable.teabag,
            R.drawable.bedsheet,
            R.drawable.file,
            R.drawable.lenghtofrope,
            R.drawable.tinofpaint,
            R.drawable.fishingrod,
            R.drawable.bedsheet,
            R.drawable.mug,
            R.drawable.handkerchief,
            R.drawable.handkerchief,
            R.drawable.fineartbrush,
            R.drawable.bottleofaftershave,
            R.drawable.rollofduct,
            R.drawable.familyphoto,
            R.drawable.ungluedfurniture,
            R.drawable.canofsoda,
            R.drawable.pieceofstring,
            R.drawable.piefilling,
            R.drawable.timber,
            R.drawable.trashbag,
            R.drawable.cratebase,
            R.drawable.timber,
            R.drawable.timber,
            R.drawable.dowel,
            R.drawable.broom,
            R.drawable.wax,
            R.drawable.dowel,
            R.drawable.icepack,
            R.drawable.sheetofpaper,
            R.drawable.bagofflour,
            R.drawable.moltenplastic,
            R.drawable.shoesole,
            R.drawable.tankofoxygen,
            R.drawable.gunmakingkit,
            R.drawable.machinereadyshoe,
            R.drawable.blanksecuritypass,
            R.drawable.crossbowbody,
            R.drawable.mouldedgun,
            R.drawable.timber
        )

        imTwoId = arrayOf(
            R.drawable.timber,
            R.drawable.soapescapists,
            R.drawable.rollofduct,
            R.drawable.razorblade,
            R.drawable.wire,
            R.drawable.razorblade,
            R.drawable.soapescapists,
            R.drawable.glassshard,
            R.drawable.rollofduct,
            R.drawable.energymodule,
            R.drawable.barofchocolate,
            R.drawable.broomhandle,
            R.drawable.timber,
            R.drawable.tinofpaint,
            R.drawable.rollofduct,
            R.drawable.battery,
            R.drawable.paperclip,
            R.drawable.energymodule,
            R.drawable.battery,
            R.drawable.file,
            R.drawable.crowbar,
            R.drawable.timber,
            R.drawable.timber,
            R.drawable.sheetofmetal,
            R.drawable.sheetofmetal,
            R.drawable.sheetofmetal,
            R.drawable.file,
            R.drawable.file,
            R.drawable.file,
            R.drawable.sturdypickaxe,
            R.drawable.dentalfloss,
            R.drawable.infirmaryoveralls,
            R.drawable.tubofbleach,
            R.drawable.pillow,
            R.drawable.rollofduct,
            R.drawable.sheetofmetal,
            R.drawable.foil,
            R.drawable.papermache,
            R.drawable.papermache,
            R.drawable.wire,
            R.drawable.pillow,
            R.drawable.rollofduct,
            R.drawable.foil,
            R.drawable.rollofduct,
            R.drawable.crowbar,
            R.drawable.lenghtofrope,
            R.drawable.bedsheet,
            R.drawable.lighter,
            R.drawable.tubeofglue,
            R.drawable.lighter,
            R.drawable.moltenplastic,
            R.drawable.plastickeys,
            R.drawable.circuitboard,
            R.drawable.moltenplastic,
            R.drawable.tuboftalcumpowder,
            R.drawable.timber,
            R.drawable.timber,
            R.drawable.lumpofsugar,
            R.drawable.lenghtofrope,
            R.drawable.tubofhandcream,
            R.drawable.lenghtofrope,
            R.drawable.tinofpaint,
            R.drawable.juicyworm,
            R.drawable.makeshiftharness,
            R.drawable.seeds,
            R.drawable.orangecolouredpen,
            R.drawable.orangecolouredpen,
            R.drawable.tinofpaint,
            R.drawable.comb,
            R.drawable.tubing,
            R.drawable.timber,
            R.drawable.tubeofglue,
            R.drawable.sugarmint,
            R.drawable.washboard,
            R.drawable.pastrycase,
            R.drawable.timber,
            R.drawable.breathingmask,
            R.drawable.bracket,
            R.drawable.nails,
            R.drawable.timber,
            R.drawable.pieceofstring,
            R.drawable.rollofduct,
            R.drawable.soapescapists,
            R.drawable.dowel,
            R.drawable.icepack,
            R.drawable.tubeofartpaints,
            R.drawable.bottleofmilk,
            R.drawable.readiedpaintbrush,
            R.drawable.shoebody,
            R.drawable.tubing,
            R.drawable.lighter,
            R.drawable.machinereadyshoe,
            R.drawable.jarofink,
            R.drawable.crossbowlathe,
            R.drawable.jarofink,
            R.drawable.paperclip
        )

        imThreeId = arrayOf(
            R.drawable.rollofduct,
            R.drawable.empty,
            R.drawable.empty,
            R.drawable.empty,
            R.drawable.razorblade,
            R.drawable.rollofduct,
            R.drawable.empty,
            R.drawable.rollofduct,
            R.drawable.empty,
            R.drawable.empty,
            R.drawable.lighter,
            R.drawable.pieceofstring,
            R.drawable.timber,
            R.drawable.rollofduct,
            R.drawable.nails,
            R.drawable.wire,
            R.drawable.rollofduct,
            R.drawable.rollofduct,
            R.drawable.empty,
            R.drawable.empty,
            R.drawable.rollofduct,
            R.drawable.rollofduct,
            R.drawable.rollofduct,
            R.drawable.rollofduct,
            R.drawable.rollofduct,
            R.drawable.rollofduct,
            R.drawable.rollofduct,
            R.drawable.rollofduct,
            R.drawable.rollofduct,
            R.drawable.rollofduct,
            R.drawable.dentalfloss,
            R.drawable.empty,
            R.drawable.empty,
            R.drawable.rollofduct,
            R.drawable.book,
            R.drawable.rollofduct,
            R.drawable.rollofduct,
            R.drawable.jarofink,
            R.drawable.empty,
            R.drawable.wire,
            R.drawable.bedsheet,
            R.drawable.empty,
            R.drawable.rollofduct,
            R.drawable.empty,
            R.drawable.rollofduct,
            R.drawable.empty,
            R.drawable.empty,
            R.drawable.pieceofstring,
            R.drawable.empty,
            R.drawable.empty,
            R.drawable.empty,
            R.drawable.empty,
            R.drawable.wire,
            R.drawable.empty,
            R.drawable.empty,
            R.drawable.timber,
            R.drawable.nails,
            R.drawable.cup,
            R.drawable.empty,
            R.drawable.nailpolish,
            R.drawable.lenghtofrope,
            R.drawable.tinofpaint,
            R.drawable.empty,
            R.drawable.empty,
            R.drawable.soil,
            R.drawable.dowel,
            R.drawable.greencolouredpen,
            R.drawable.empty,
            R.drawable.dentalfloss,
            R.drawable.handkerchief,
            R.drawable.tubeofglue,
            R.drawable.empty,
            R.drawable.empty,
            R.drawable.tubeofglue,
            R.drawable.empty,
            R.drawable.empty,
            R.drawable.rollofduct,
            R.drawable.empty,
            R.drawable.empty,
            R.drawable.bolts,
            R.drawable.tubeofglue,
            R.drawable.radioreceiver,
            R.drawable.empty,
            R.drawable.rollofduct,
            R.drawable.rollofduct,
            R.drawable.fineartbrush,
            R.drawable.lumpofsugar,
            R.drawable.tubeofglue,
            R.drawable.empty,
            R.drawable.rollofduct,
            R.drawable.dinnertray,
            R.drawable.empty,
            R.drawable.feather,
            R.drawable.tubeofglue,
            R.drawable.empty,
            R.drawable.pieceofstring
        )

        imageId = arrayOf(
            R.drawable.baseball,
            R.drawable.sockandmolotok,
            R.drawable.glassshank,
            R.drawable.combblade,
            R.drawable.whip,
            R.drawable.superwhip,
            R.drawable.makeshiftcosh,
            R.drawable.makeshiftspear,
            R.drawable.knuckleduster,
            R.drawable.superknuckleduster,
            R.drawable.cupofmoltenchocolate,
            R.drawable.makeshiftdoublebass,
            R.drawable.nunchacks,
            R.drawable.makeshiftsledgehammer,
            R.drawable.superbat,
            R.drawable.energymodule,
            R.drawable.makeshiftstungun,
            R.drawable.supermetalbaton,
            R.drawable.supersockmace,
            R.drawable.toolhandle,
            R.drawable.flimsypickaxe,
            R.drawable.lightweightpickaxe,
            R.drawable.sturdypickaxe,
            R.drawable.flimsyshovel,
            R.drawable.lightweightshovel,
            R.drawable.sturdyshovel,
            R.drawable.flimsycutters,
            R.drawable.lightweightcutters,
            R.drawable.sturdycutters,
            R.drawable.multitool,
            R.drawable.cuttingfloss,
            R.drawable.guardoutfit,
            R.drawable.infirmaryoveralls,
            R.drawable.cushionedinmateoutfit,
            R.drawable.paddedinmateoutfit,
            R.drawable.platedinmateoutfit,
            R.drawable.makeshiftrobotguardoutfit,
            R.drawable.fakewallblock,
            R.drawable.fakeventcover,
            R.drawable.fakefence,
            R.drawable.beddummy,
            R.drawable.contrabandpouch,
            R.drawable.durablecontrabandpouch,
            R.drawable.poster,
            R.drawable.grapplehead,
            R.drawable.grapplinghook,
            R.drawable.sheetrope,
            R.drawable.candle,
            R.drawable.papermache,
            R.drawable.moltenplastic,
            R.drawable.plastickeys,
            R.drawable.keymould,
            R.drawable.keycardmould,
            R.drawable.keycards,
            R.drawable.wadofputty,
            R.drawable.timberbrace,
            R.drawable.cratebase,
            R.drawable.cupoftea,
            R.drawable.gliderskin,
            R.drawable.manicurekit,
            R.drawable.makeshiftharness,
            R.drawable.makeshiftladder,
            R.drawable.readiedfishingrod,
            R.drawable.parachute,
            R.drawable.pottedplant,
            R.drawable.pretendflower,
            R.drawable.pretendcarrot,
            R.drawable.readiedpaintbrush,
            R.drawable.visitorskit,
            R.drawable.breathingmask,
            R.drawable.framedphoto,
            R.drawable.gluereadiedfurniture,
            R.drawable.makeshiftrocketthruster,
            R.drawable.musicwashboard,
            R.drawable.uncookedpie,
            R.drawable.ungluedfurniture,
            R.drawable.breathabletrashbag,
            R.drawable.cratecasing,
            R.drawable.cratetop,
            R.drawable.crossbowbody,
            R.drawable.crossbowlathe,
            R.drawable.fakeaudioequipment,
            R.drawable.gunmakingkit,
            R.drawable.halfframeofglider,
            R.drawable.heartrateslower,
            R.drawable.beautifulpainting,
            R.drawable.cake,
            R.drawable.escapistsfigurine,
            R.drawable.machinereadyshoe,
            R.drawable.makeshiftbreathingapparatus,
            R.drawable.mouldedgun,
            R.drawable.pairofshoes,
            R.drawable.securitypass,
            R.drawable.completecrossbow,
            R.drawable.fakegun,
            R.drawable.fishingrod
        )
        name = arrayOf(
            getString(R.string.baseball_bat),
            getString(R.string.sock_mase),
            getString(R.string.glass_shank),
            getString(R.string.comb_blade),
            getString(R.string.whip),
            getString(R.string.super_whip),
            getString(R.string.makeshift_cosh),
            getString(R.string.makeshift_spear),
            getString(R.string.knuckle_duster),
            getString(R.string.super_knuckle_duster),
            getString(R.string.cup_of_molten_chocolate),
            getString(R.string.makeshift_double_bass),
            getString(R.string.nunchucks),
            getString(R.string.makeshift_sledgehammer),
            getString(R.string.super_baseball_bat),
            getString(R.string.energy_module),
            getString(R.string.makeshift_stungun),
            getString(R.string.super_metal_baton),
            getString(R.string.super_sock_mace),
            getString(R.string.tool_handle),
            getString(R.string.flimsy_pickaxe),
            getString(R.string.lightweight_pickaxe),
            getString(R.string.sturdy_pickaxe),
            getString(R.string.flimsy_shovel),
            getString(R.string.lightweight_shovel),
            getString(R.string.sturdy_shovel),
            getString(R.string.flimsy_cutters),
            getString(R.string.lightweight_cutters),
            getString(R.string.sturdy_cutters),
            getString(R.string.multitool),
            getString(R.string.cutting_floss),
            getString(R.string.guard_outfit),
            getString(R.string.infirmary_overalls),
            getString(R.string.cushioned_inmate_outfit),
            getString(R.string.padded_inmate_outfit),
            getString(R.string.plated_Inmate_outfit),
            getString(R.string.makeshift_robot_guard_outfit),
            getString(R.string.fake_wall_block),
            getString(R.string.fake_vent_cover),
            getString(R.string.fake_fence),
            getString(R.string.bed_dummy),
            getString(R.string.contraband_pouch),
            getString(R.string.durable_contraband_pouch),
            getString(R.string.poster),
            getString(R.string.grapple_head),
            getString(R.string.grappling_hook),
            getString(R.string.sheet_rope),
            getString(R.string.candle),
            getString(R.string.paper_mache),
            getString(R.string.molten_plastic),
            getString(R.string.plastic_key),
            getString(R.string.key_mold),
            getString(R.string.keycard_mould),
            getString(R.string.fake_keycards),
            getString(R.string.wad_of_putty),
            getString(R.string.timber_brace),
            getString(R.string.crate_base),
            getString(R.string.cup_of_tea),
            getString(R.string.glider_skin),
            getString(R.string.manicure_kit),
            getString(R.string.makeshift_harness),
            getString(R.string.makeshift_ladder),
            getString(R.string.readied_fishing_rod),
            getString(R.string.parachute),
            getString(R.string.potted_plant),
            getString(R.string.pretend_flower),
            getString(R.string.pretend_carrot),
            getString(R.string.readied_paint_brush),
            getString(R.string.visitors_kit),
            getString(R.string.breathing_mask),
            getString(R.string.framed_photo),
            getString(R.string.glue_readied_furniture),
            getString(R.string.makeshift_rocket_thruster),
            getString(R.string.music_washboard),
            getString(R.string.uncooked_pie),
            getString(R.string.unglued_furniture),
            getString(R.string.breathable_trash_bag),
            getString(R.string.crate_casing),
            getString(R.string.crate_top),
            getString(R.string.crossbow_body),
            getString(R.string.crossbow_lathe),
            getString(R.string.fake_audio_equipment),
            getString(R.string.gun_making_kit),
            getString(R.string.half_frame_of_glider),
            getString(R.string.heart_rate_slower),
            getString(R.string.beautiful_painting),
            getString(R.string.cake),
            getString(R.string.escapists_figurine),
            getString(R.string.machine_ready_shoe),
            getString(R.string.makeshift_breathing_apparatus),
            getString(R.string.moulded_gun),
            getString(R.string.pair_of_shoes),
            getString(R.string.security_pass),
            getString(R.string.complete_crossbow),
            getString(R.string.fake_gun),
            getString(R.string.fishing_rod)
        )

        craft = arrayOf(
            getString(R.string.baseball_bat_craft),
            getString(R.string.sock_mase_craft),
            getString(R.string.glass_shank_craft),
            getString(R.string.comb_blade_craft),
            getString(R.string.whip_craft),
            getString(R.string.super_whip_craft),
            getString(R.string.makeshift_cosh_craft),
            getString(R.string.makeshift_spear_craft),
            getString(R.string.knuckle_duster_craft),
            getString(R.string.super_knuckle_duster_craft),
            getString(R.string.cup_of_molten_chocolate_craft),
            getString(R.string.makeshift_double_bass_craft),
            getString(R.string.nunchucks_craft),
            getString(R.string.makeshift_sledgehammer_craft),
            getString(R.string.super_baseball_bat_craft),
            getString(R.string.energy_module_craft),
            getString(R.string.makeshift_stungun_craft),
            getString(R.string.super_metal_baton_craft),
            getString(R.string.super_sock_mace_craft),
            getString(R.string.tool_handle_craft),
            getString(R.string.flimsy_pickaxe_craft),
            getString(R.string.lightweight_pickaxe_craft),
            getString(R.string.sturdy_pickaxe_craft),
            getString(R.string.flimsy_shovel_craft),
            getString(R.string.lightweight_shovel_craft),
            getString(R.string.sturdy_shovel_craft),
            getString(R.string.flimsy_cutters_craft),
            getString(R.string.lightweight_cutters_craft),
            getString(R.string.sturdy_cutters_craft),
            getString(R.string.multitool_craft),
            getString(R.string.cutting_floss_craft),
            getString(R.string.guard_outfit_craft),
            getString(R.string.infirmary_overalls_craft),
            getString(R.string.cushioned_inmate_outfit_craft),
            getString(R.string.padded_inmate_outfit_craft),
            getString(R.string.plated_Inmate_outfit_craft),
            getString(R.string.makeshift_robot_guard_outfit_craft),
            getString(R.string.fake_wall_block_craft),
            getString(R.string.fake_vent_cover_craft),
            getString(R.string.fake_fence_craft),
            getString(R.string.bed_dummy_craft),
            getString(R.string.contraband_pouch_craft),
            getString(R.string.durable_contraband_pouch_craft),
            getString(R.string.poster_craft),
            getString(R.string.grapple_head_craft),
            getString(R.string.grappling_hook_craft),
            getString(R.string.sheet_rope_craft),
            getString(R.string.candle_craft),
            getString(R.string.paper_mache_craft),
            getString(R.string.molten_plastic_craft),
            getString(R.string.plastic_key_craft),
            getString(R.string.key_mold_craft),
            getString(R.string.keycard_mould_craft),
            getString(R.string.fake_keycards_craft),
            getString(R.string.wad_of_putty_craft),
            getString(R.string.timber_brace_craft),
            getString(R.string.crate_base_craft),
            getString(R.string.cup_of_tea_craft),
            getString(R.string.glider_skin_craft),
            getString(R.string.manicure_kit_craft),
            getString(R.string.makeshift_harness_craft),
            getString(R.string.makeshift_ladder_craft),
            getString(R.string.readied_fishing_rod_craft),
            getString(R.string.parachute_craft),
            getString(R.string.potted_plant_craft),
            getString(R.string.pretend_flower_craft),
            getString(R.string.pretend_carrot_craft),
            getString(R.string.readied_paint_brush_craft),
            getString(R.string.visitors_kit_craft),
            getString(R.string.breathing_mask_craft),
            getString(R.string.framed_photo_craft),
            getString(R.string.glue_readied_furniture_craft),
            getString(R.string.makeshift_rocket_thruster_craft),
            getString(R.string.music_washboard_craft),
            getString(R.string.uncooked_pie_craft),
            getString(R.string.unglued_furniture_craft),
            getString(R.string.breathable_trash_bag_craft),
            getString(R.string.crate_casing_craft),
            getString(R.string.crate_top_craft),
            getString(R.string.crossbow_body_craft),
            getString(R.string.crossbow_lathe_craft),
            getString(R.string.fake_audio_equipment_craft),
            getString(R.string.gun_making_kit_craft),
            getString(R.string.half_frame_of_glider_craft),
            getString(R.string.heart_rate_slower_craft),
            getString(R.string.beautiful_painting_craft),
            getString(R.string.cake_craft),
            getString(R.string.escapists_figurine_craft),
            getString(R.string.machine_ready_shoe_craft),
            getString(R.string.makeshift_breathing_apparatus_craft),
            getString(R.string.moulded_gun_craft),
            getString(R.string.pair_of_shoes_craft),
            getString(R.string.security_pass_craft),
            getString(R.string.complete_crossbow_craft),
            getString(R.string.fake_gun_craft),
            getString(R.string.fishing_rod_craft)
        )

        intelligence = arrayOf(
            "40+",
            "40+",
            "40+",
            "40+",
            "40+",
            "60+",
            "70+",
            "40+",
            "60+",
            "50+",
            "60+",
            "50+",
            "50+",
            "60+",
            "60+",
            "70+",
            "60+",
            "60+",
            "70+",
            "60+",
            "40+",
            "40+",
            "50+",
            "60+",
            "40+",
            "50+",
            "60+",
            "40+",
            "50+",
            "60+",
            "70+",
            "40+",
            "40+",
            "50+",
            "40+",
            "50+",
            "60+",
            "50+",
            "40+",
            "30+",
            "50+",
            "40+",
            "60+",
            "70+",
            "30+",
            "50+",
            "70+",
            "30+",
            "40+",
            "40+",
            "50+",
            "60+",
            "50+",
            "50+",
            "60+",
            "40+",
            "30+",
            "30+",
            "30+",
            "30+",
            "30+",
            "30+",
            "30+",
            "30+",
            "30+",
            "30+",
            "30+",
            "30+",
            "30+",
            "30+",
            "40+",
            "40+",
            "40+",
            "40+",
            "40+",
            "40+",
            "40+",
            "50+",
            "50+",
            "50+",
            "50+",
            "50+",
            "50+",
            "50+",
            "50+",
            "50+",
            "60+",
            "60+",
            "60+",
            "60+",
            "60+",
            "60+",
            "60+",
            "60+",
            "70+",
            "70+",
            "70+"
        )

        for (i in imageId.indices) {
            val items = Items(
                imageId[i],
                name[i],
                craft[i],
                intelligence[i],
                imOneId[i],
                imTwoId[i],
                imThreeId[i]
            )
            itemsArrayList.add(items)
        }
    }
}